# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: nft-agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install --force
  displayName: 'npm install'

# - script: |
#      npm audit fix --force
#   displayName: 'npm audit force'

- script: |
    npm run build
  displayName: 'npm build'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo rm -rf  /usr/local/tomcat8/webapps/ROOT/'
  displayName: clean build directory 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd /datadrive/new-nftagent/_work/1/a'
  displayName: change to artifact directory 

    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo cp -R build /usr/local/tomcat8/webapps/ROOT/ '
  displayName: deploy to tomcat
